# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: write # for creating release + uploading binaries

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Update continuous tag to latest commit
        uses: EndBug/latest-tag@latest
        with:
          ref: continuous
      
      - name: Create a release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: continuous
          prerelease: true
          name: "Continuous Build"
          body: |
            This is a continuous build release.

            It will always contain a build of the latest version of the code in the main branch.

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install build dependenties
        run: |
          mkdir build &&
          sudo apt update -y &&
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
        #run: sudo apt install libstdc++-arm-none-eabi-newlib #test if this is really needed

      - name: Get Pico SDK and dependenties
        run: | #https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines
          git clone https://github.com/raspberrypi/pico-sdk.git --branch master && \
          cd pico-sdk && \
          git submodule update --init && \
          cd ..

#      #picoprobe used as an example, should be the source in this repository
#      - name: Compile RP2040 source
#        run: | 
#          git clone https://github.com/raspberrypi/picoprobe.git && \
#          cd picoprobe && \
#          git submodule update --init && \
#          mkdir build && \
#          cd build && \
#          export PICO_SDK_PATH=../../pico-sdk && \
#          cmake .. && \
#          make && \
#          cd ..

      - name: Compile RP2040 source
        run: | 
          mkdir -p build && \
          cd build && \
          export PICO_SDK_PATH=../pico-sdk && \
          cmake .. && \
          make && \
          cd ..

      #upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_tag: "continuous"
          compress_assets: 'OFF' # Do not put in .zip/.tar.gz
          md5sum: 'OFF' # Do not add bloaty .md5 files
          name: full build directory
          path: |
            build/cable-tester/cable-tester.uf2